# Site settings
title: Anyi Guo
email: yanniey.guo@gmail.com
url: https://github.com/yanniey
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F2BC79 #80B3FF
  secondary: DD1111 #FD6E8A
  secondary-dark: 1A3640 #A2122F

# Footer settings
footer:
  copyright: Anyi Guo
  location: Chicago, IL
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/AnyiGuo
  - title: instagram
    url: http://instagram.com/yanniey318
  - title: github
    url: https://github.com/yanniey
  - title: tumblr
    url: http://anyiguo.tumblr.com/


# Postal address (add as many lines as necessary)
address:
  - line: But I might be anywhere around the world. 
  - line: twitter me @AnyiGuo

# Credits content
credits: 'Creating my first single page site with <a href="http://jekyllrb.com/">Jekyll</a>.'

# Build settings
markdown: kramdown
permalink: pretty
